title: Alexander J. Gray Engineering Portfolio
description: "A portfolio for my experience in biomedical engineering, specializing in biomedical optics, instrumentation, image processing, and machine learning"
baseurl: ""
url: "https://alexgray103.github.io"
author:
  name: Alexander J. Gray
  email: algray@bu.edu

# Remove theme (no Minima)
theme: null  

# Jekyll functionality without a theme
include: ["_pages"]
paginate: false
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation Links
nav_links:
  Home: "/"
  About: "/about"
  Projects: "/projects"

# Enable custom pages (instead of blog posts)
collections:
  pages:
    output: true
    permalink: /:path/
