title: Alexander J. Gray Engineering Portfolio
description: "A portfolio for my experience in biomedical engineering, specializing in biomedical optics, instrumentation, image processing and machine learning"
baseurl: ""
url: "https://alexgray103.github.io"
author:
  name: Alexander J. Gray
  email: algray@bu.edu


theme: minima # Use GitHub's default Jekyll theme (or change later)
baseurl: "" # Leave blank for GitHub Pages

# Navigation links
nav_links:
  Home: "/"
  About: "/about"
  Projects: "/projects"
