title: My Portfolio
description: "A portfolio site showcasing my projects"
baseurl: ""
url: "https://alexgray103.github.io"
author:
  name: Alexander J. Gray
  email: algray@bu.edu


theme: minima # Use GitHub's default Jekyll theme (or change later)
baseurl: "" # Leave blank for GitHub Pages
url: "https://your-username.github.io" # Your site URL

# Navigation links
nav_links:
  Home: "/"
  About: "/about"
  Projects: "/projects"
