title: "Alexander J. Gray - Engineering Portfolio"
description: "An engineering portfolio showcasing experience in biomedical optics, image processing, and machine learning."
baseurl: ""
url: "https://alexgray103.github.io/AlexG_Portfolio/"

theme: jekyll-theme-hacker
include: ["_layouts", "_pages"]


# Navigation links
nav_links:
  Home: "https://alexgray103.github.io/AlexG_Portfolio"
  About: "/about"
  Projects: "/projects"
  Publications: "/Publications"



